### ISSUE TITLE
default model are not taken from the config file.

### ISSUE THREAD

**Issue by calathus** [egoist/shell-ask#10]
ask "what is git" will ask to select model even if default model is set up in config file.
following code will fix this issue.

ask.ts
  let modelId =
    (typeof options.model === "string" ? options.model : config.default_model? config.default_model:"select") || // <== modified
    chat?.options.realModelId ||
    config.default_model ||
    "gpt-3.5-turbo"

**Comment by egoist** [comment]
fixed in 0.0.31

**Comment by egoist** [comment]
just reinstall it: 

```
# or pnpm
npm i -g shell-ask@latest 
```
