### ISSUE TITLE
how to set 

### ISSUE THREAD

**Issue by nikitavoloboev** [egoist/shell-ask#11]
I have `llama3:8b-instruct-q5_K_M` model with ollama

How to set it with config, its unclear

<img width="428" alt="image" src="https://github.com/egoist/shell-ask/assets/6391776/bc978764-4df0-491d-bca8-da7d78aed68f">

tried above but get

<img width="1685" alt="image" src="https://github.com/egoist/shell-ask/assets/6391776/fe789a36-fd7c-4ab0-acb2-23497956111b">

**Comment by egoist** [comment]
you need to add a `ollama-` prefix, run `ask list` to view the list of models

**Comment by nikitavoloboev** [comment]
thanks that worked
