### ISSUE TITLE
how to pipe things into shell-ask

### ISSUE THREAD

**Issue by nikitavoloboev** [egoist/shell-ask#12]
`ls | ask explain files` does not work but does with pure ollama

**Comment by nikitavoloboev** [comment]
<img width="764" alt="image" src="https://github.com/egoist/shell-ask/assets/6391776/9df4e3cd-9049-4eb7-aadf-9acf16b2949d">

**Comment by egoist** [comment]
your command should work, some small models are not good enough to understand the context though

![CleanShot 2024-06-07 at 03 27 56@2x](https://github.com/egoist/shell-ask/assets/8784712/4b67d2f1-6683-461d-9c5f-f7c4ace91d24)

**Comment by egoist** [comment]
you can use `DEBUG` environment variable to verify the messages:
![CleanShot 2024-06-07 at 03 29 40@2x](https://github.com/egoist/shell-ask/assets/8784712/38469a14-8276-48e7-98bb-b4ec414535db)
