### ISSUE TITLE
Allow the output from Shell Ask to be piped to another command

### ISSUE THREAD

**Issue by geekdada** [egoist/shell-ask#13]
Both the actual output from the LLM and the status updates are currently being sent to `stdout`, making it impossible to pipe the output to another command, such as another `ask` command.

It is suggested to log irrelevant information to `stderr` to keep the `stdout` pure, could you also make it so?

Thank you for creating such a great tool!

**Comment by egoist** [comment]
it works for me tho

![CleanShot 2024-06-17 at 16 29 20@2x](https://github.com/egoist/shell-ask/assets/8784712/17360fc2-52e7-4b73-be44-b8a7f3d45d49)

**Comment by geekdada** [comment]
Maybe I shouldn't have used `ask` as an example here because LLM is smart enough to discard the irrelevant information 😄 
If you look at the `stdin` in the second command you'd know 😄

**Comment by geekdada** [comment]
@egoist any updates :)
