### ISSUE TITLE
Add copilot support

### ISSUE THREAD

**Issue by enlewof** [egoist/shell-ask#17]
Copilot also has a command line interface, but I really like the piping shell-ask provides: https://docs.github.com/en/copilot/using-github-copilot/using-github-copilot-in-the-command-line

I can try to help with this as best I can, but wanted to start the issue in public and see thoughts.

**Comment by egoist** [comment]
I just added Copilot Chat support, you can upgrade to 0.0.38 and follow the instruction here: https://github.com/egoist/shell-ask#copilot-chat

**Comment by enlewof** [comment]
Awesome.  Thank you
