### ISSUE TITLE
FR: Expand shell variables in 

### ISSUE THREAD

**Issue by nbbaier** [egoist/shell-ask#6]
This is a really neat tool! It would be great if shell variable expansion (or something similar) would be possible in the config file. For example, it would be nice if the following worked:

```json
{
    "openai_api_key": "$OPENAI_API_KEY"
}
```

This would make it easier to store the config file in git.

**Comment by egoist** [comment]
now it will read env var as default value https://github.com/egoist/shell-ask/blob/main/docs/config.md#openai_api_key-optional

**Comment by nbbaier** [comment]
Really great, thanks!
